spring.application.name=superadmin
spring.datasource.url=jdbc:mysql://localhost:3306/dbbbplus?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Tami@sha1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA & Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tamisharani123@gmail.com
spring.mail.password=majcgbgcrumvvqcz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
file.upload.path=D:/Partner/


setu.base-url=https://dg-sandbox.setu.co

# setu.client-id=YOUR_SETU_CLIENT_ID
# setu.client-secret=YOUR_SETU_CLIENT_SECRET

# # PAN verification product instance
# setu.pan-product-id=YOUR_PAN_PRODUCT_INSTANCE_ID

# # DigiLocker product instance
# setu.digilocker-product-key=YOUR_DIGILOCKER_PRODUCT_INSTANCE_ID

setu.client-id=f779548b-73b3-4044-a629-e3d9949dea9a
setu.client-secret=Y9GwGhZ0uZodVmBJvKkz4FNM1DDxBVWk

setu.digilocker-product-key=d9d80500-eec8-47ad-bed2-ee74972cb874




 String loginLink = "https://partner.yourcompany.com/login";
    String body = """
            <html>
            <body style="font-family:Arial,sans-serif; background:#f4f6f9;padding:20px;">
              <div style="max-width:600px;margin:auto; background:#ffffff;border-radius:10px; overflow:hidden;">
                <div style="background:#28a745; color:white;padding:20px; text-align:center;">
                  <h2>Application Approved 🎉</h2>
                </div>
                <div style="padding:25px;">
                  <p>Dear <b>%s</b>,</p>
                  <p>Congratulations! Your Channel Partner application has been approved.</p>
                  <table style="width:100%%; border-collapse:collapse; background:#f8f9fa;">
                    <tr>
                      <td style="padding:10px;"><b>Partner Code</b></td>
                      <td style="padding:10px;">%s</td>
                    </tr>
                    <tr>
                      <td style="padding:10px;"><b>Partner Plan</b></td>
                      <td style="padding:10px;">%s</td>
                    </tr>
                  </table>
                  <br>
                  <a href="%s" style="background:#007bff; color:white;padding:12px 20px; text-decoration:none; border-radius:5px;">
                    Login Portal
                  </a>
                  <br><br>
                  <p>Regards,<br><b>Admin Team</b></p>
                </div>
              </div>
            </body>
            </html>
            """.formatted(
                    savedPartner.getContactPerson(),
                    savedPartner.getPartnerCode(),
                    savedPartner.getTierName(),
                    loginLink
            );
